/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
<<<<<<< HEAD
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAjudaRouteImport } from './routes/_authenticated/ajuda'
import { Route as AuthenticatedBabaRouteImport } from './routes/_authenticated/baba'
import { Route as AuthenticatedCartinhasRouteImport } from './routes/_authenticated/cartinhas'
import { Route as AuthenticatedConquistasRouteImport } from './routes/_authenticated/conquistas'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedPagamentosRouteImport } from './routes/_authenticated/pagamentos'
=======
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtualizarCadastroRouteImport } from './routes/atualizar-cadastro'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
>>>>>>> 6d9582fdcebeaabad4b69e19a66ae2c04d92fa60
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPagamentosRouteImport } from './routes/_authenticated/pagamentos'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedCartinhasRouteImport } from './routes/_authenticated/cartinhas'
import { Route as AuthenticatedBabaRouteImport } from './routes/_authenticated/baba'
import { Route as AuthenticatedAjudaRouteImport } from './routes/_authenticated/ajuda'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago-webhook'
import { Route as ApiAuthConfirmarEmailRouteImport } from './routes/api/auth/confirmar-email'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminSorteioRouteImport } from './routes/_authenticated/admin/sorteio'
import { Route as AuthenticatedAdminResultadosRouteImport } from './routes/_authenticated/admin/resultados'
import { Route as AuthenticatedAdminFinanceiroRouteImport } from './routes/_authenticated/admin/financeiro'
import { Route as AuthenticatedAdminEstatisticasRouteImport } from './routes/_authenticated/admin/estatisticas'
import { Route as AuthenticatedAdminCargosRouteImport } from './routes/_authenticated/admin/cargos'
import { Route as AuthenticatedAdminAjudaRouteImport } from './routes/_authenticated/admin/ajuda'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtualizarCadastroRoute = AtualizarCadastroRouteImport.update({
  id: '/atualizar-cadastro',
  path: '/atualizar-cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const AuthenticatedConquistasRoute = AuthenticatedConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
=======
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
>>>>>>> 6d9582fdcebeaabad4b69e19a66ae2c04d92fa60
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPagamentosRoute = AuthenticatedPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartinhasRoute = AuthenticatedCartinhasRouteImport.update({
  id: '/cartinhas',
  path: '/cartinhas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBabaRoute = AuthenticatedBabaRouteImport.update({
  id: '/baba',
  path: '/baba',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAjudaRoute = AuthenticatedAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago-webhook',
    path: '/api/public/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthConfirmarEmailRoute = ApiAuthConfirmarEmailRouteImport.update({
  id: '/api/auth/confirmar-email',
  path: '/api/auth/confirmar-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSorteioRoute =
  AuthenticatedAdminSorteioRouteImport.update({
    id: '/sorteio',
    path: '/sorteio',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminResultadosRoute =
  AuthenticatedAdminResultadosRouteImport.update({
    id: '/resultados',
    path: '/resultados',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceiroRoute =
  AuthenticatedAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEstatisticasRoute =
  AuthenticatedAdminEstatisticasRouteImport.update({
    id: '/estatisticas',
    path: '/estatisticas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCargosRoute =
  AuthenticatedAdminCargosRouteImport.update({
    id: '/cargos',
    path: '/cargos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAjudaRoute = AuthenticatedAdminAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atualizar-cadastro': typeof AtualizarCadastroRoute
  '/auth': typeof AuthRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/baba': typeof AuthenticatedBabaRoute
  '/cartinhas': typeof AuthenticatedCartinhasRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/ajuda': typeof AuthenticatedAdminAjudaRoute
  '/admin/cargos': typeof AuthenticatedAdminCargosRoute
  '/admin/estatisticas': typeof AuthenticatedAdminEstatisticasRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/resultados': typeof AuthenticatedAdminResultadosRoute
  '/admin/sorteio': typeof AuthenticatedAdminSorteioRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/auth/confirmar-email': typeof ApiAuthConfirmarEmailRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atualizar-cadastro': typeof AtualizarCadastroRoute
  '/auth': typeof AuthRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/baba': typeof AuthenticatedBabaRoute
  '/cartinhas': typeof AuthenticatedCartinhasRoute
  '/conquistas': typeof AuthenticatedConquistasRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/admin/ajuda': typeof AuthenticatedAdminAjudaRoute
  '/admin/cargos': typeof AuthenticatedAdminCargosRoute
  '/admin/estatisticas': typeof AuthenticatedAdminEstatisticasRoute
  '/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/admin/resultados': typeof AuthenticatedAdminResultadosRoute
  '/admin/sorteio': typeof AuthenticatedAdminSorteioRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/auth/confirmar-email': typeof ApiAuthConfirmarEmailRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/atualizar-cadastro': typeof AtualizarCadastroRoute
  '/auth': typeof AuthRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/ajuda': typeof AuthenticatedAjudaRoute
  '/_authenticated/baba': typeof AuthenticatedBabaRoute
  '/_authenticated/cartinhas': typeof AuthenticatedCartinhasRoute
  '/_authenticated/conquistas': typeof AuthenticatedConquistasRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/pagamentos': typeof AuthenticatedPagamentosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/admin/ajuda': typeof AuthenticatedAdminAjudaRoute
  '/_authenticated/admin/cargos': typeof AuthenticatedAdminCargosRoute
  '/_authenticated/admin/estatisticas': typeof AuthenticatedAdminEstatisticasRoute
  '/_authenticated/admin/financeiro': typeof AuthenticatedAdminFinanceiroRoute
  '/_authenticated/admin/resultados': typeof AuthenticatedAdminResultadosRoute
  '/_authenticated/admin/sorteio': typeof AuthenticatedAdminSorteioRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/auth/confirmar-email': typeof ApiAuthConfirmarEmailRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atualizar-cadastro'
    | '/auth'
    | '/esqueci-senha'
    | '/recuperar-senha'
    | '/sitemap.xml'
    | '/admin'
    | '/ajuda'
    | '/baba'
    | '/cartinhas'
    | '/conquistas'
    | '/inicio'
    | '/pagamentos'
    | '/perfil'
    | '/admin/ajuda'
    | '/admin/cargos'
    | '/admin/estatisticas'
    | '/admin/financeiro'
    | '/admin/resultados'
    | '/admin/sorteio'
    | '/admin/usuarios'
    | '/api/auth/confirmar-email'
    | '/api/public/mercadopago-webhook'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atualizar-cadastro'
    | '/auth'
    | '/esqueci-senha'
    | '/recuperar-senha'
    | '/sitemap.xml'
    | '/ajuda'
    | '/baba'
    | '/cartinhas'
    | '/conquistas'
    | '/inicio'
    | '/pagamentos'
    | '/perfil'
    | '/admin/ajuda'
    | '/admin/cargos'
    | '/admin/estatisticas'
    | '/admin/financeiro'
    | '/admin/resultados'
    | '/admin/sorteio'
    | '/admin/usuarios'
    | '/api/auth/confirmar-email'
    | '/api/public/mercadopago-webhook'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/atualizar-cadastro'
    | '/auth'
    | '/esqueci-senha'
    | '/recuperar-senha'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/ajuda'
    | '/_authenticated/baba'
    | '/_authenticated/cartinhas'
    | '/_authenticated/conquistas'
    | '/_authenticated/inicio'
    | '/_authenticated/pagamentos'
    | '/_authenticated/perfil'
    | '/_authenticated/admin/ajuda'
    | '/_authenticated/admin/cargos'
    | '/_authenticated/admin/estatisticas'
    | '/_authenticated/admin/financeiro'
    | '/_authenticated/admin/resultados'
    | '/_authenticated/admin/sorteio'
    | '/_authenticated/admin/usuarios'
    | '/api/auth/confirmar-email'
    | '/api/public/mercadopago-webhook'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AtualizarCadastroRoute: typeof AtualizarCadastroRoute
  AuthRoute: typeof AuthRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAuthConfirmarEmailRoute: typeof ApiAuthConfirmarEmailRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atualizar-cadastro': {
      id: '/atualizar-cadastro'
      path: '/atualizar-cadastro'
      fullPath: '/atualizar-cadastro'
      preLoaderRoute: typeof AtualizarCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/_authenticated/conquistas': {
      id: '/_authenticated/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof AuthenticatedConquistasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
=======
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
>>>>>>> 6d9582fdcebeaabad4b69e19a66ae2c04d92fa60
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagamentos': {
      id: '/_authenticated/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof AuthenticatedPagamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cartinhas': {
      id: '/_authenticated/cartinhas'
      path: '/cartinhas'
      fullPath: '/cartinhas'
      preLoaderRoute: typeof AuthenticatedCartinhasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/baba': {
      id: '/_authenticated/baba'
      path: '/baba'
      fullPath: '/baba'
      preLoaderRoute: typeof AuthenticatedBabaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ajuda': {
      id: '/_authenticated/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AuthenticatedAjudaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/mercadopago-webhook': {
      id: '/api/public/mercadopago-webhook'
      path: '/api/public/mercadopago-webhook'
      fullPath: '/api/public/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/confirmar-email': {
      id: '/api/auth/confirmar-email'
      path: '/api/auth/confirmar-email'
      fullPath: '/api/auth/confirmar-email'
      preLoaderRoute: typeof ApiAuthConfirmarEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sorteio': {
      id: '/_authenticated/admin/sorteio'
      path: '/sorteio'
      fullPath: '/admin/sorteio'
      preLoaderRoute: typeof AuthenticatedAdminSorteioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/resultados': {
      id: '/_authenticated/admin/resultados'
      path: '/resultados'
      fullPath: '/admin/resultados'
      preLoaderRoute: typeof AuthenticatedAdminResultadosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/financeiro': {
      id: '/_authenticated/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/estatisticas': {
      id: '/_authenticated/admin/estatisticas'
      path: '/estatisticas'
      fullPath: '/admin/estatisticas'
      preLoaderRoute: typeof AuthenticatedAdminEstatisticasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cargos': {
      id: '/_authenticated/admin/cargos'
      path: '/cargos'
      fullPath: '/admin/cargos'
      preLoaderRoute: typeof AuthenticatedAdminCargosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ajuda': {
      id: '/_authenticated/admin/ajuda'
      path: '/ajuda'
      fullPath: '/admin/ajuda'
      preLoaderRoute: typeof AuthenticatedAdminAjudaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAjudaRoute: typeof AuthenticatedAdminAjudaRoute
  AuthenticatedAdminCargosRoute: typeof AuthenticatedAdminCargosRoute
  AuthenticatedAdminEstatisticasRoute: typeof AuthenticatedAdminEstatisticasRoute
  AuthenticatedAdminFinanceiroRoute: typeof AuthenticatedAdminFinanceiroRoute
  AuthenticatedAdminResultadosRoute: typeof AuthenticatedAdminResultadosRoute
  AuthenticatedAdminSorteioRoute: typeof AuthenticatedAdminSorteioRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAjudaRoute: AuthenticatedAdminAjudaRoute,
  AuthenticatedAdminCargosRoute: AuthenticatedAdminCargosRoute,
  AuthenticatedAdminEstatisticasRoute: AuthenticatedAdminEstatisticasRoute,
  AuthenticatedAdminFinanceiroRoute: AuthenticatedAdminFinanceiroRoute,
  AuthenticatedAdminResultadosRoute: AuthenticatedAdminResultadosRoute,
  AuthenticatedAdminSorteioRoute: AuthenticatedAdminSorteioRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAjudaRoute: typeof AuthenticatedAjudaRoute
  AuthenticatedBabaRoute: typeof AuthenticatedBabaRoute
  AuthenticatedCartinhasRoute: typeof AuthenticatedCartinhasRoute
  AuthenticatedConquistasRoute: typeof AuthenticatedConquistasRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedPagamentosRoute: typeof AuthenticatedPagamentosRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAjudaRoute: AuthenticatedAjudaRoute,
  AuthenticatedBabaRoute: AuthenticatedBabaRoute,
  AuthenticatedCartinhasRoute: AuthenticatedCartinhasRoute,
  AuthenticatedConquistasRoute: AuthenticatedConquistasRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedPagamentosRoute: AuthenticatedPagamentosRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AtualizarCadastroRoute: AtualizarCadastroRoute,
  AuthRoute: AuthRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAuthConfirmarEmailRoute: ApiAuthConfirmarEmailRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
